# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-26 03:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('cant_jugadores', models.CharField(max_length=50, verbose_name=b'Cantidad Jugadores')),
                ('precio', models.CharField(max_length=10, verbose_name=b'Precio')),
                ('techada', models.BooleanField(default=False, verbose_name=b'Techada')),
                ('luz', models.BooleanField(default=False, verbose_name=b'Luz')),
            ],
            options={
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Facebook')),
                ('twitter', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Twitter')),
                ('direccion', models.CharField(max_length=250, verbose_name=b'Direccion')),
                ('patrocinador', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Patrocinador')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('vestuarios', models.BooleanField(default=False, verbose_name=b'Vestuarios')),
                ('duchas', models.BooleanField(default=False, verbose_name=b'Duchas')),
                ('bar', models.BooleanField(default=False, verbose_name=b'Bar')),
                ('restaurant', models.BooleanField(default=False, verbose_name=b'Restaurant')),
                ('parrilla', models.BooleanField(default=False, verbose_name=b'Parrilla')),
                ('wifi', models.BooleanField(default=False, verbose_name=b'Wifi')),
                ('tv', models.BooleanField(default=False, verbose_name=b'TV')),
                ('seguridad', models.BooleanField(default=False, verbose_name=b'Seguridad')),
                ('estacionamiento', models.BooleanField(default=False, verbose_name=b'Estacionamiento')),
                ('tarjetas', models.BooleanField(default=False, verbose_name=b'Tarjeta Debito/Credito')),
                ('festejos', models.BooleanField(default=False, verbose_name=b'Festejos')),
                ('escuelita', models.BooleanField(default=False, verbose_name=b'Escuelita')),
                ('torneos', models.BooleanField(default=False, verbose_name=b'Torneos')),
                ('colegios', models.BooleanField(default=False, verbose_name=b'Colegios')),
            ],
            options={
                'verbose_name_plural': 'Complejos',
            },
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Deportes',
            },
        ),
        migrations.CreateModel(
            name='ImagenesCanchas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=b'canchas/')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cancha')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Cancha',
            },
        ),
        migrations.CreateModel(
            name='ImagenesComplejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=b'complejos/')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Complejo',
            },
        ),
        migrations.CreateModel(
            name='Reputacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputacion', models.CharField(max_length=10, verbose_name=b'Reputacion')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('fecha', models.CharField(default=b'00000000', max_length=8, verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name_plural': 'Reputacion',
            },
        ),
        migrations.CreateModel(
            name='ReputacionComplejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo')),
                ('reputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Reputacion')),
            ],
            options={
                'verbose_name_plural': 'Reputaciones Complejo',
            },
        ),
        migrations.CreateModel(
            name='ReputacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('reputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Reputacion')),
            ],
            options={
                'verbose_name_plural': 'Reputaciones Usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name=b'Nombre')),
                ('telefono', models.CharField(max_length=15, verbose_name=b'Telefono')),
                ('fecha_inicio', models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Inicio')),
                ('fecha_fin', models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Fin')),
                ('precio', models.CharField(max_length=10, verbose_name=b'Precio')),
                ('sena', models.CharField(max_length=10, verbose_name=b'Senia')),
                ('pago', models.CharField(max_length=10, verbose_name=b'Pago')),
                ('evento', models.BooleanField(default=False, verbose_name=b'Evento')),
                ('fecha_cracion', models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha creacion')),
                ('fecha_atualizacion', models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Actualizacion')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Superficies',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=250, verbose_name=b'Telefono')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='TelefonosComplejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Telefono')),
            ],
            options={
                'verbose_name_plural': 'Telefonos Complejo',
            },
        ),
        migrations.CreateModel(
            name='TelefonosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Telefono')),
            ],
            options={
                'verbose_name_plural': 'Telefonos Usuario',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Telefono',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('es_admin', models.BooleanField(default=False, verbose_name=b'Es Administrador')),
                ('es_usuario', models.BooleanField(default=False, verbose_name=b'Es Usuario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha creacion')),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoUsuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuariosComplejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='telefonosusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipoTelefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoTelefono'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por', to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Cancha'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoReserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='reputacionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Complejo'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Deporte'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='superficie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Superficie'),
        ),
    ]
