# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 17:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesCanchas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=b'canchas/')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cancha')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesComplejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=b'complejos/')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Reputacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputacion', models.CharField(max_length=10, verbose_name=b'Reputacion')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name=b'Fecha')),
            ],
            options={
                'verbose_name_plural': 'Reputacion',
            },
        ),
        migrations.CreateModel(
            name='ReputacionComplejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Reputaciones Complejo',
            },
        ),
        migrations.CreateModel(
            name='ReputacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('reputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Reputacion')),
            ],
            options={
                'verbose_name_plural': 'Reputaciones Usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Inicio')),
                ('fechaFin', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Fin')),
                ('precio', models.CharField(max_length=10, verbose_name=b'Precio')),
                ('sena', models.CharField(max_length=10, verbose_name=b'Senia')),
                ('pago', models.CharField(max_length=10, verbose_name=b'Pago')),
                ('evento', models.BooleanField(default=False, verbose_name=b'Evento')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Cancha')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=250, verbose_name=b'Telefono')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='TelefonosComplejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Telefonos Complejo',
            },
        ),
        migrations.CreateModel(
            name='TelefonosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Telefono')),
            ],
            options={
                'verbose_name_plural': 'Telefonos Usuario',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Reserva',
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Telefono',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name=b'Nombre')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name=b'Comentario')),
                ('esAdmin', models.BooleanField(default=False, verbose_name=b'Es Administrador')),
                ('esUsuario', models.BooleanField(default=False, verbose_name=b'Es Usuario')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuaurio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoUsuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AlterField(
            model_name='complejo',
            name='direccion',
            field=models.CharField(max_length=250, verbose_name=b'Direccion'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='facebook',
            field=models.CharField(max_length=250, verbose_name=b'Facebook'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='patrocinador',
            field=models.CharField(max_length=250, verbose_name=b'Patrocinador'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='twitter',
            field=models.CharField(max_length=250, verbose_name=b'Twitter'),
        ),
        migrations.AddField(
            model_name='telefonosusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='telefonoscomplejo',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo'),
        ),
        migrations.AddField(
            model_name='telefonoscomplejo',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Telefono'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipoTelefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoTelefono'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipoReserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.TipoReserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='reputacionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='reputacioncomplejo',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo'),
        ),
        migrations.AddField(
            model_name='reputacioncomplejo',
            name='reputacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Reputacion'),
        ),
        migrations.AddField(
            model_name='imagenescomplejos',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo'),
        ),
    ]
