# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160822_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Facebook'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='patrocinador',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Patrocinador'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Twitter'),
        ),
    ]
