# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160824_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosComplejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Complejo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cancha',
            options={'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='imagenescanchas',
            options={'verbose_name_plural': 'Imagenes Cancha'},
        ),
        migrations.AlterModelOptions(
            name='imagenescomplejos',
            options={'verbose_name_plural': 'Imagenes Complejo'},
        ),
        migrations.RenameField(
            model_name='cancha',
            old_name='cantJugadores',
            new_name='cant_jugadores',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='tipoReserva',
            new_name='tipo_reserva',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='esAdmin',
            new_name='es_admin',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='esUsuario',
            new_name='es_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUsuaurio',
            new_name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por', to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_atualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Actualizacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cracion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Fecha creacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default='Telefonico', max_length=30, verbose_name=b'Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(default='155...', max_length=15, verbose_name=b'Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='luz',
            field=models.BooleanField(default=False, verbose_name=b'Luz'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='techada',
            field=models.BooleanField(default=False, verbose_name=b'Techada'),
        ),
        migrations.AlterField(
            model_name='reputacion',
            name='fecha',
            field=models.DateField(default=datetime.date(2016, 9, 8), verbose_name=b'Fecha'),
        ),
        migrations.AddField(
            model_name='usuarioscomplejos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
    ]
