# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160908_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputacion',
            name='fecha',
            field=models.CharField(default=b'00000000', max_length=8, verbose_name=b'Fecha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_atualizacion',
            field=models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Actualizacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_cracion',
            field=models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.CharField(default=b'000000000000', max_length=12, verbose_name=b'Fecha creacion'),
        ),
    ]
