# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-28 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reserva_id_res'),
        ('web', '0005_auto_20161125_1654'),
    ]

    operations = [
    ]
